from datetime import datetime


def generate_report(
    pipeline_id: str,
    project_path: str,
    mr_title: str,
    mr_iid: str,
    author: str,
    commit_sha: str,
    failed_job: str,
    failure_log: str,
    changed_files: list,
    blast_radius_files: list,
    llm_summary: str,
    confidence: int = 85
) -> str:
    """
    Generate the full markdown Root Cause & Impact Analysis Report.
    This is the primary output of the OrbitFix-AI agent.
    """

    changed_files_md = "\n".join(
        [f"- `{f}`" for f in changed_files]
    ) if changed_files else "- No changed files detected"

    blast_radius_md = "\n".join(
        [f"- `{f}`" for f in blast_radius_files]
    ) if blast_radius_files else "- No dependent files detected (isolated change)"

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    report = f"""# 🔍 Orbit Root Cause & Impact Analysis Report

**Project:** `{project_path}`
**Pipeline:** #{pipeline_id}
**Generated:** {timestamp}

---

## Failure Source

| Field | Value |
|---|---|
| Merge Request | !{mr_iid} — {mr_title} |
| Author | {author} |
| Commit | `{commit_sha[:8] if commit_sha else "unknown"}` |
| Failed Job | `{failed_job}` |

---

## Evidence

### Failure Log (relevant section)
```
{failure_log[-1500:] if failure_log else "No log available"}
```

### AI Summary
{llm_summary}

---

## Changed Files (MR !{mr_iid})

{changed_files_md}

---

## Impact Analysis (Blast Radius)

Files that depend on the changed code — these are **at risk**:

{blast_radius_md}

---

## Confidence

**{confidence}%** — based on Orbit relationship graph traversal

> Orbit traced the failure through {len(changed_files)} changed file(s)
> and identified {len(blast_radius_files)} potentially impacted file(s).

---

## Recommended Action

{"⚠️ **Rollback** MR !" + str(mr_iid) + " or update all dependent imports listed above." if blast_radius_files else "✅ Change appears isolated — review the failed job log for the specific error."}

---

*Generated by [OrbitFix-AI](https://gitlab.com/m.adnan4637-group/orbitfix-ai-dev) — Orbit-powered root cause & impact analysis*
"""

    return report


def generate_minimal_report(error: str) -> str:
    """Fallback report when Orbit data is unavailable."""
    return f"""# ⚠️ OrbitFix-AI — Analysis Incomplete

Unable to complete full Orbit analysis.

**Error:** {error}

Please check:
- Orbit is enabled on your group
- GitLab token has `api` scope
- The project is indexed in Orbit

*OrbitFix-AI agent*
"""
